### ISSUE TITLE
Error in rule phenograph: Input matrix consists only of NaN entries.

### ISSUE THREAD

**Issue by JohannesGawron** [ETH-NEXUS/scAmpi_single_cell_RNA#22]
# Description
A ValueError(Input X contains NaN.) is thrown in line 92 of the `apply_phenograph.py` script causing the pipeline to crash. I checked the input file `results/counts_corrected/GFB-7820.corrected.variable_genes.h5` quickly to see that the count matrix contains only NaNs.

# Log Report

I checked the log-file of the preceding rule `sctransform_preprocessing` to see that  NAs seem to show up already after calling the function `sctransform::smooth_via_pca` (see screenshot below):
![Screenshot 2023-09-11 at 16 04 46](https://github.com/ETH-NEXUS/scAmpi_single_cell_RNA/assets/93670909/e07add71-0c64-4637-84ed-04e241fbe0e1)
It looks like the actual variance stabilisation step is done without any issues, at least I get a meaningful output plot:
![GFB-7820 mean_vs_variance_plot](https://github.com/ETH-NEXUS/scAmpi_single_cell_RNA/assets/93670909/de865485-8c8c-4ef3-8767-a7294ed43e2f)

# Parameters

I ran the pipeline as suggested in the README if this repo with the following parameters:

```
 filter_genes_and_cells:
    nmads_fractionMT: "100"
    nmads_NODG: "100"
    threshold_NODG: "400"
    threshold_fractionMT: "0.5"
    genomeVersion: "GRCh38"
    remove_doublets: "TRUE"
    protein_coding_only: "FALSE"
    minNumberCells: "20"

  sctransform_preprocessing:
    number_genes: "2000"
    min_var: "1.5"
    n_nn: "30"
```
I'd appreciate if you could help me with this.
